### ISSUE TITLE
[REQUEST] Throwables from cars

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#105]
_transferred from ticket 5513_

**Provide an overview for your feature request:**

You buy or aquire the item like a snowball or something and throw it

**Describe how your feature request would work:**

It would be fun in rp and could be a good thing a like a sports thiung or something

**How does this feature request benefit you in particular?**

Be able to throw things from cars

**Who else does this feature request benefit?**

It would be fun in rp and could be a good thing a like a sports thiung or something

**What would be required to implement your request?**

I dont know but hopefully not to much.

**Comment by GhostDaGhost** [comment]
We could add a baseball... but where would you get snowballs from if it's sunny?

**Comment by GhostDaGhost** [comment]
Added baseball to hardware store.
