### ISSUE TITLE
[REQUEST]  Own 2nd Home 

### ISSUE THREAD

**Issue by TulaPlays** [ProductionRP/Feature-Requests#108]
ticket-5980

**Provide an overview for your feature request:**

Allow characters to own a second home.

**Describe how your feature request would work:**

Limit is raised from 1 home to 2 homes.

**How does this feature request benefit you in particular?**

Me personally? Makes no difference. However being a realtor and speaking with people daily about houses it seems there are more people trying and/or wanting to buy a second home than there are people wanting to buy their first. Housing market is still flooded with available properties with only Grapeseed being fully bought out so there is still plenty of availability with no worries of their being nothing left for new players. 

**Who else does this feature request benefit?**

All players wanting a second home whether it be for a vacation home, stash house, buy it for a friend etc. 

Besides yourself, who does your feature request benefit?

**What would be required to implement your request?**

(dont hurt me if Im wrong) but Id assume just changing the line prohibiting more than 1 to more than 2.

We understand you might not be a developer, but any information you can provide regarding what could be required to implement your suggestion is useful!

**Comment by GhostDaGhost** [comment]
Suggestion denied for now.
