### ISSUE TITLE
[REQUEST] Dynamic Holster Script

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#112]
_transferred from ticket 6104_

**Provide an overview for your feature request:**

Dynamic Holsters

**Describe how your feature request would work:**

i think its just a script or something. when you pull out a gun, the holster actually shows an actual empty holster

**How does this feature request benefit you in particular?**

REALISM AND IT LOOKS STUPID

**Who else does this feature request benefit?**

cops and everyone wearing a holster and fans of REALISM

**What would be required to implement your request?**

i think not a lot but if its a lot i'm able to learn how to do this and then do it myself
https://forum.cfx.re/t/release-dynamic-holsters-eup-support/731182

**Comment by GhostDaGhost** [comment]
We don't have empty holsters currently in our clothing mix. Denied for now.
