### ISSUE TITLE
[REQUEST] More card types in wallet

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#116]
_transferred from ticket 5877_

**Provide an overview for your feature request:**

Be able to put business cards in wallets.

**Describe how your feature request would work:**

Putting business cards into wallet, self explanatory.

**How does this feature request benefit you in particular?**
Just makes sense since it's a type of card, and would like to be organized.

**Who else does this feature request benefit?**

Everyone with a wallet, making it easier to organize inventory.

**What would be required to implement your request?**

Don't think this would be too much work.

**Comment by GhostDaGhost** [comment]
Implemented next restart.
