### ISSUE TITLE
[REQUEST] DoJ MDT

### ISSUE THREAD

**Issue by itstait** [ProductionRP/Feature-Requests#14]
Imported - `ticket-2572`

**Provide an overview for your feature request:**

Entry level DOJ MDT!

**Describe how your feature request would work:**

It would be a reduced access MDT for lawyers and paralegals to use that will reduce the risk of information leaks.
It would require a contacts list for all citizens, allowing for a flow of communication, the report search function, and access to the whole penal code. Also personal notes.
Anything else can be accessed by the senior level and above on the current MDT's.

**How does this feature request benefit you in particular?**

To reduce the security risk of giving new lawyers and paralegals absolute access in the current MDT's. They still need to do their job, and won't need anything more than reports access and the penal code.

**Who else does this feature request benefit?**

DOJ, and public interest. Reduced risk of intel leaks, and better access to relevant information for the lawyers and paralegals.

**What would be required to implement your request?**

Not sure, hopefully minimal. But I think the contacts list would be a new addition I guess.

**Comment by stubbers92** [comment]
@GhostDaGhost With the changes that you will be making to the perms for SASP etc is this something that we could do?

**Comment by GhostDaGhost** [comment]
Implemented.
