### ISSUE TITLE
[REQUEST] LEO Ticket/ Bill Confirmation

### ISSUE THREAD

**Issue by itstait** [ProductionRP/Feature-Requests#19]
Imported - `ticket-2694`

**Provide an overview for your feature request:**

When SP use the command /bill we don't get any sort of notification that its went through or that the person has received it other than the small notice at the top right saying you issued the bill but there is no way to confirm they actually received it like with a traffic ticket, they have to sign it and a little message in the chat box pops up.  I'd like to propose the same kind of system.

**Describe how your feature request would work:**

When we bill someone, they would be required to sign stating they received it and the trooper who issued the bill would be notified that its been signed and they received it successfully.

**How does this feature request benefit you in particular?**

To prevent accidental multiple bills and confirmation the person has received said bill.

**Who else does this feature request benefit?**

SASP and the civilian currently being billed so they are aware of the bill

**What would be required to implement your request?**

It would work off the same system as /ticket so I wouldn't imagine it would require much to implement.

**Comment by GhostDaGhost** [comment]
Suggestion approved and already implemented.
