### ISSUE TITLE
[REQUEST] Visual Indicator for /triageself

### ISSUE THREAD

**Issue by itstait** [ProductionRP/Feature-Requests#22]
Imported - `ticket-2802`

**Provide an overview for your feature request:**

Force an animation similar to inventory opening or putting on a vest for the self triage option. Showing something visual for when someone enters into the triage section as people walking up to you to triage you and having no way of knowing that they are, or in an individual standpoint when you are around people, you can signify that you are starting first aid on you or someone else

**Describe how your feature request would work:**

An emote like the inventory or bullet proof vest animation

**How does this feature request benefit you in particular?**

Just thought it would be cool with the plethora of other custom ideas that have been implemented.

**Who else does this feature request benefit?**

Everyone, it would signify someone entering into the medical menu and prompt more vocal responses from yourself and those around you.

**What would be required to implement your request?**

Unknown
it could even be something like the MDT /me's and something like "jack has started looking themself over for injuries" or "X is checking X over for injuries"

**Comment by GhostDaGhost** [comment]
Suggestion approved and already implemented.
