### ISSUE TITLE
[REQUEST] Gun shot injuries take longer to heal

### ISSUE THREAD

**Issue by itstait** [ProductionRP/Feature-Requests#24]
Imported - `ticket-3066`

**Provide an overview for your feature request:**

Gun shots take longer to revive at the hospital.

**Describe how your feature request would work:**

Gun shots are seriously, HIGH fatal risk. Takes longer to pull out bullets/revive in hospital.

**How does this feature request benefit you in particular?**

For people to stop getting in shootings, go lay in a bed for 30-60 seconds then book it out the hospital. Yes, this is failRP on a medical point but people do it SO much that I think it needs a macro approach.

**Who else does this feature request benefit?**

Server, encourages pacing.

**What would be required to implement your request?**

Dev work. Unsure, I barely know how to turn on Solitaire half the time.

**Comment by GhostDaGhost** [comment]
Suggestion approved and already implemented.
