### ISSUE TITLE
[REQUEST] Use /forcestretcher to move patients from stretcher to bed

### ISSUE THREAD

**Issue by itstait** [ProductionRP/Feature-Requests#28]
Imported - `ticket-3084`

**Provide an overview for your feature request:**

To use /forcestretcher for transferring patients from the stretcher to the hospital bed

**Describe how your feature request would work:**

I presume it would be something like the current /forcestretcher?

**How does this feature request benefit you in particular?**

Its very clunky and immersion breaking to F2>Take from stretcher> /escort > F2>Put person on bed. I don't think it looks very professional taking the person from the stretcher and dumping them on the floor.

**Who else does this feature request benefit?**

Both EMTs and patients, for speed/smoothness and realism.

**What would be required to implement your request?**

At a guess, as much work as /forcestretcher required.

**Comment by GhostDaGhost** [comment]
Suggestion approved and already has been implemented.
