### ISSUE TITLE
[REQUEST] Save hairstyles like outfits

### ISSUE THREAD

**Issue by itstait** [ProductionRP/Feature-Requests#29]
Imported - `ticket-2631`

**Provide an overview for your feature request:**

Add a way to save hairstyles 

**Describe how your feature request would work:**

Would work similar to outfits for those that switch between hair styles/colors frequently.

**How does this feature request benefit you in particular?**

To easily switch between my characters hair and the wig she regularly wairs.

**Who else does this feature request benefit?**

Anyone whos character changes their hair frequently.

**What would be required to implement your request?**

Not much, I imagine it would be just taking the outfit saving system and adding to hair

**Comment by GhostDaGhost** [comment]
Suggestion denied. This would take the point away from barbershops.
