### ISSUE TITLE
[REQUEST] Give Cop's weapons that take .45 ammo

### ISSUE THREAD

**Issue by Plebbles** [ProductionRP/Feature-Requests#30]
What is your suggestion?: Give cops Glocks that take .45 ammo

How would it work?: Give cops Glocks that take .45 ammo

Why do you in particular want this?:the 9mm takes 5 shots to down someone, civs take 2 to 3, or 1 with a revolver or musket

Who would this benefit , and how?: Police cause our guns suck

How much work would be required?: I have no idea

**Comment by GhostDaGhost** [comment]
Cops can use Heavy Pistols now.
