### ISSUE TITLE
[REQUEST] Finishing Mechanics

### ISSUE THREAD

**Issue by Plebbles** [ProductionRP/Feature-Requests#40]
What is your suggestion?: Modify Fishing Mechanics

How would it work?: No minigame or raise pay per fish

Why do you in particular want this?: I'm just comparing it to other events that involve a mini game, i.e lockpicking cash registers/drilling atms, hacking. I feel a lot of non-rewarding results from fishing which is im sure not the intention, the whole ocean could be utilized if fishing was more rewarding. Fishing is a legal job but requires work and you compare it to like towing etc that don't have minigames, to keep it balanced it could be good. If not that, raising the price per fish could be good when you compare the work to reward ratio of fishing to say towing.

Who would this benefit , and how?: Legal RP, citizen RP, Job RP, atm feeling is more recreational but It would be nice to see more people doing it for monetary gain.

How much work would be required?: Not sure, maybe the pricing balance may take a few minutes to adjust.

**Comment by GhostDaGhost** [comment]
Suggestion denied. You get better at fishing anyways.
