### ISSUE TITLE
[REQUEST] In Game Evidence Board for Court Rooms

### ISSUE THREAD

**Issue by Plebbles** [ProductionRP/Feature-Requests#42]
What is your suggestion?:

- A way to display evidence in a court room on a monitor that everyone sees, not in form of a scene. However if we have a picture of evidence, the ability to be able to put it on a monitor somewhere etc. so everyone can see will make things easier rather than us having to have people link witnesses the court dockets and making them search for the evidence we want them to look at.

How would it work?: 

- The way I imagine it working is that you setup a polyzone at the two tables of the attorneys, then one at the Judges bench. and when people use the radial menu in the polyzone they get access to change the picture that is being displayed.

Why do you in particular want this?:

- Simplicity in court cases, not also be a great asset to court RP. Also making it easier for both attorneys, viewers and also witnesses so we don't have to link the court case docket for everyone etc.

Who would this benefit , and how?:

- Listed above pretty much, unless further explanation is required.

How much work would be required?:

- Well- setting up polyzones literally takes 30 seconds, the MOST time consuming thing I see is finding a place to display things accordingly, I don't remember if there are any monitors in the new court room off the top of my head right now.

**Comment by GhostDaGhost** [comment]
This was implemented for MRPD's classroom however courtroom doesn't have a place to put one.
