### ISSUE TITLE
[REQUEST] Style ID to Barbershop

### ISSUE THREAD

**Issue by Plebbles** [ProductionRP/Feature-Requests#44]
What is your suggestion?: Add style id numbers to barbershop and makeup sliders

How would it work?: There would be a box with the id number of the different colors and stuff next to the sliders same as with the different clothing options

Why do you in particular want this?: Because switching between set styles with no easy way to note down (or save) the settings makes switching between regularly used hairs and makeups very frustrating

Who would this benefit , and how?: Anyone that like to have different hair/looks or make use of wigs in roleplay

How much work would be required?: Not much I would imagine, I'm sure the different options already have the ID numbers for saving into the database and the interface already has a text box that shows it for other things.
![image](https://user-images.githubusercontent.com/67167952/174359316-119b9744-d4eb-4b9e-b61e-caaed5edba68.png)

**Comment by GhostDaGhost** [comment]
Input boxes added to hair color/hair highlight color boxes.

**Comment by GhostDaGhost** [comment]
Added input boxes to makeup boxes.
