### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by SommerTheViking** [ProductionRP/Feature-Requests#45]
**Provide an overview for your feature request:**

Make it possible to plant weed plants inside houses

**Describe how your feature request would work:**

Very simple, allow players to plant weed plants inside of a house

**How does this feature request benefit you in particular?**

it benefits not only me but everyone having their stuff in peace and not spreading plants and/or their lag to random locations

**Who else does this feature request benefit?**

Everyone

**What would be required to implement your request?**

Remove the current script that blocks players from doing so currently

**Comment by GhostDaGhost** [comment]
Denied. This is in store for gangs.
