### ISSUE TITLE
[REQUEST] Decay on food

### ISSUE THREAD

**Issue by N3ibs** [ProductionRP/Feature-Requests#47]
**Provide an overview for your feature request:**

Use this space to provide us with an overview of how your suggestion could work.

All food would decay and have more people interact with the many business restaurants & or cook more often

Use as much detail as possible to describe your request's inner workings. If this area is lacking when reviewed, the development team may ask you to clarify your original request.

**How does this feature request benefit you in particular?**

I just think it will provide more RP to the many food businesses i myself dont own it 

**Who else does this feature request benefit?**

restaurant owners and its employees and in general everyone as its a way more fun thing to do

**What would be required to implement your request?**

i have no idea

**Comment by GhostDaGhost** [comment]
In planning phase.
