### ISSUE TITLE
[REQUEST] Add more gang signs 

### ISSUE THREAD

**Issue by ItsNeibs** [ProductionRP/Feature-Requests#49]
**Provide an overview for your feature request:**

Add additional gang signs to allow gang members to express themselves through emotes.

**Describe how your feature request would work:**
(https://youtu.be/ZnQdfWbNw3o - an example video with some gang sign emotes. )

**How does this feature request benefit you in particular?**

Gangs frequently use these to express passion for their colours/gang in character, and it adds to the immersion. From personal experience when playing as a non gang member and seeing them throw up some gang signs, it adds to the feel of realism and can make your civ/cop character feel more intimidated.

**Who else does this feature request benefit?**

It would benefit everyone I believe. Mainly gangs, as they'd be able to express themselves using unique gang signs. There's currently only two gang signs in the city (/e gangsign and /e gangsign2). From other servers, gang sign 1 tends to be used by GSF and number 2 by Ballas. Considering we have neither gangs really active at the moment, it'd be great to see some more gang signs added for other gangs to use. It would also benefit other players experiencing the gang signs, adding to the immersion and realism of the situation. I personally think that emotes are such a small part of the server, but can provide massive amounts of in depth details to a situation to make it just that little bit more realistic for others.

**What would be required to implement your request?**

I assume very minimal as there'll be premade emotes like in the video above where you could just copy the animations into the server files.

**Comment by GhostDaGhost** [comment]
Those emotes are encrypted and needing to be tied to a CFX account. It also may require a whole another resource to be made just to maintain the encryption of these emotes. Until a free solution is made, these specific ones will not be added.
