### ISSUE TITLE
[REQUEST] Prompt if wearing seatbelt

### ISSUE THREAD

**Issue by ItsNeibs** [ProductionRP/Feature-Requests#53]
**Provide an overview for your feature request:**

A prompt showing if someone in a vehicle is not wearing a seat belt.  Would be nice if there we're a way to have a visible seat belt that appears over the shoulder if wearing one, but unsure how difficult that would be.

**Describe how your feature request would work:**

A command or radius prompt that would appear to someone outside of a vehicle if near the driver or passenger side of said vehicle.

**How does this feature request benefit you in particular?**

There is currently an option for the use of seatbelts but no way to identify if someone is wearing one.  This would allow for seatbelt laws to come into effect and encourage people to put the seatbelt function to use more often.

**Who else does this feature request benefit?**

Everyone, civilians would be more encouraged to use the seatbelt more often if they might be penalized with a citation if they don't.  Although I know some would still keep seatbelts "off" until pulled over than could quickly put it on.  If a visible representation of a seat belt is possible, this could allow others to see it at a distance rather than having to be close to the vehicle.

**What would be required to implement your request?**

For the prompt, just a checklist if person has seatbelt "off" than prompt is given.  If visual representation is made, unsure as that could be anything from a makeshift clothing item that spawns, or emote, or some texture.  Idk.

**Comment by GhostDaGhost** [comment]
Unfortunately, not possible to do easily.
