### ISSUE TITLE
[REQUEST] Mod-Shop HEX / RGB Paint Code

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#62]
Transferred from Ticket 3895

**Provide an overview for your feature request:** 
Permit mechanic jobs access to a HEX / RGB Paint option

**Describe how your feature request would work:**
When mechanics apply paint, permit a HEX / RBG menu for custom color selection 

**How does this feature request benefit you in particular?**
Expand business options for mechanic shops.

**Who else does this feature request benefit?** 
All mechanics and players who wish to have unique cars.

**What would be required to implement your request?**
Development of new UI
Determine what color pallet options are available for GTA 5

**Comment by GhostDaGhost** [comment]
Denied due to mechanic limitations. This is a **disabled** feature but will need to investigate how to properly go about it.
