### ISSUE TITLE
[REQUEST] Female Ped Biker Vests

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#65]
**Transfer from Ticket 4362** 

**Provide an overview for your feature request:** Addition of biker vests that better support female MP Peds

Addition of biker vests that better support female MP Peds

**Describe how your feature request would work:**

add in item to clothing section

**How does this feature request benefit you in particular?**

so female bikers have a better option for a vest in the vest category to wear over more clothing

**Who else does this feature request benefit?**

all female bikers

**What would be required to implement your request?**

id imagine not a lot

**Comment by GhostDaGhost** [comment]
Already implemented I believe?
