### ISSUE TITLE
[REQUEST] Remove player prompt from /bill

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#71]
**Provide an overview for your feature request:**

The /bill command for ES/LEO will ask the player to sign it. Remove the action for the player to be able to refuse or sign the bill. It’s weird when SASP arrest someone and sends them a bill and they refuse it but they will still be billed.

**Describe how your feature request would work:**

All functions of the existing /bill command, with the exception of the player being asked to sign the bill.

**How does this feature request benefit you in particular?**

Not having someone refuse the bill, which still bills them, before sending players to prison. 

**Who else does this feature request benefit?**

Other LEOs and criminals who are being billed.

**What would be required to implement your request?**

Removal of the player check on the bill.

**Comment by GhostDaGhost** [comment]
Implemented next restart.
