### ISSUE TITLE
[REQUEST] Increase Vehicle Damage

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#75]
_Transferred from ticket 4745_

**Provide an overview for your feature request:**

Use this space to provide us with an overview of how your suggestion could work.

**Describe how your feature request would work:**

Vehicles when they crash could lose tyres, pop tyres, break

**How does this feature request benefit you in particular?**

Because currently I am being rammed by cars in chases at 100+ mph, I go flying and because of the way I like to RP, I stop. But theyll continue ramming like nothing happened. Or they’ll crash into a tree, and their car ain’t even scratched. 

**Who else does this feature request benefit?**

Everyone. It would provide a more realistic set of roleplay for all with driving. You’d drive more sensibly even in chases because you know one stupid crash could fuck you up. Little bumps and scrapes are fine. But anything hard will take you out.

**What would be required to implement your request?**

A fair amount. A lot of fine tuning for a lot of cars. But I think needed to stop the car shitlording rn. I shouldn’t be able to be rammed by a sports car, that irl would break easily, and have him continue without scratches.

**Comment by GhostDaGhost** [comment]
System currently being experimented.
