### ISSUE TITLE
[REQUEST] Hide in a tent

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#84]
_transferred from ticket 4916_

**Provide an overview for your feature request:**

Make tents something you can enter similar to hiding in a dumpster

**Describe how your feature request would work:**

similar to dumpsters, but with tents

**How does this feature request benefit you in particular?**

allow you to create your own hiding spot as well as access some others that are already existing

**Who else does this feature request benefit?**

Anyone on the run from the law or trying to do stakeouts and wanna remain inconspicuous 

**What would be required to implement your request?**

Apply the dumpster feature to the tent props.

**Comment by GhostDaGhost** [comment]
Implemented next restart.
