### ISSUE TITLE
[REQUEST] UI overlay for when /status is set

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#88]
_transferred from 4950_

**Provide an overview for your feature request:**

An indicator for when you have a status set

**Describe how your feature request would work:**

Just a UI overlay for a status

**How does this feature request benefit you in particular?**

I keep forgetting to clear my status

**Who else does this feature request benefit?**

Everyone, but mostly me

**What would be required to implement your request?**

Idk.

**Comment by GhostDaGhost** [comment]
Implemented next restart.
