### ISSUE TITLE
[REQUEST] Phone app notifications

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#89]
**Provide an overview for your feature request:**

a visual notifier, such as a little red number on the calls, texts, and possibly bleeter and yellow page apps to show if you have unseen/unread calls/messages.

**Describe how your feature request would work:**

If you have an 'unread' text or unanswered call the icon would have a little red something to 'yell' at you about it.

**How does this feature request benefit you in particular?**

It's been something i've been wanting for a while, but now as BBB it will help me organize myself more to make sure i'm not missing anything in the 'spam' times

**Who else does this feature request benefit?**

Everyone, but mostly people who get a lot of 'digital contact' or those who are contacted while asleep

**What would be required to implement your request?**

I am unsure honestly as I don't know what's needed to make a phone work to begin with

**Comment by Morril** [comment]
@Plebbles really wants this.

**Comment by GhostDaGhost** [comment]
Implemented next restart.
