### ISSUE TITLE
[REQUEST] Show value stolen from store thefts

### ISSUE THREAD

**Issue by itstait** [ProductionRP/Feature-Requests#9]
Imported - `ticket-2083`

**Provide an overview for your feature request:**

Make it so officers can get information on how much money was stolen from the register and safes from the cashier

**Describe how your feature request would work:**

go to the register/safe and check it

**How does this feature request benefit you in particular?**

Extra information from a NPC that cant talk can go a long way

**Who else does this feature request benefit?**

everyone. cops can see how much was stolen for investigations and criminals or innocence civilians wont get charged with the wrong crime if no money was taken

**What would be required to implement your request?**

SOE had it but not sure how hard to put in here

**Comment by GhostDaGhost** [comment]
Suggestion approved and already implemented.
