### ISSUE TITLE
[REQUEST] New RVs 

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#92]
_Transferred from ticket 5141_

**Provide an overview for your feature request:**

Add new RVs that permit interior links

**Describe how your feature request would work:**

It's a caravan... You can actually go into.

**How does this feature request benefit you in particular?**

It's a caravan... You can actually go into.

**Who else does this feature request benefit?**

Caravan owners.

**What would be required to implement your request?**

Depends on how much work you want to put into it. Replacement? None. Addon, Some. If you need me to make an RV seller business just to get these things here I will. I WILL

**Comment by GhostDaGhost** [comment]
Not possible.
