### ISSUE TITLE
[REQUEST] Vehicle Damage Script

### ISSUE THREAD

**Issue by Morril** [ProductionRP/Feature-Requests#93]
**Provide an overview for your feature request:**

Add a vehicle damage script 

**Describe how your feature request would work:**

Add a script like the one use for personal injury, that would better represent damage to vehicle damage. Currently vehicle damage is completely unrealistic and doesn’t accurately represent damage.

**How does this feature request benefit you in particular?**

I believe it’s hard to provide realistic, serious RP when cars can roll 9 times and drive away. I think we would get higher quality RP if there was a better way to represent how the vehicle was damaged and how that damage would effect the performance.

**Who else does this feature request benefit?**

The community at large would benefit from having a more accurate representation of damage to their vehicle, creating better RP. Mechanic shops would benefit from by being able to provide more services.

**What would be required to implement your request?**

Unknown, I know a few scripts exist but not sure if they are any good

**Comment by GhostDaGhost** [comment]
Basic damage script added for next restart.
